# Generated by Django 2.2.24 on 2023-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231209_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца')),
                ('phonenumber', models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца')),
                ('pure_phonenumber', models.CharField(db_index=True, max_length=20, verbose_name='Нормализованный номер владельца')),
                ('flats', models.ManyToManyField(db_index=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
