# Generated by Django 2.2.24 on 2023-12-09 16:35

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            defaults={
                'phonenumber': flat.owners_phonenumber,
                'pure_phonenumber': flat.owner_pure_phone,
            }
        )
        
        flat.owners.set([owner])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20231209_1647'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners),
    ]